http:
  services:
    webapp:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: 'https://florance-webui-app.internal.{{ env "CONTAINER_APP_ENV_DNS_SUFFIX" }}'
  routers:
    menuitem:
      rule: "Path(`/`)"
      service: florance-webui-app
