entryPoints:
  web:
    address: ":80"
providers:
  file:
    directory: "/etc/traefik/dynamic"
log:
  level: DEBUG
http:
  middlewares:
    traefik-forward-auth:
      forwardAuth:
        address: "https://example.com/auth"
