http:
  services:
    chat-service:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: 'https://florance-chat-app.internal.{{ env "CONTAINER_APP_ENV_DNS_SUFFIX" }}/conversation'
  routers:
    menuitem:
      rule: "Path(`/api/conversation`)"
      service: chat-service
